{
 "title": "SNMP Dashboard",
 "description": "For snmp exporter with dot1dStpPortState",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "STPport", "query": "dot1dStpPortState" },
   {
    "name": "Interface",
    "query": "query_result(ifInOctets{job=\"snmp-exporter\"})"
   },
   {
    "name": "Internal_Interface",
    "query": "query_result(ifInOctets{job=\"snmp-exporter\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Internal_Interface'}[5m])",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Internal_Interface'}[5m])",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  { "title": "Ports Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Port Status - $STPport",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "repeat": "STPport",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dot1dStpPortState{dot1dStpPort=\"$STPport\"}"
    }
   ]
  },
  { "title": "Ports Utilize", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$Interface util",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "repeat": "Interface",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(irate(ifHCOutOctets{ifDescr=\"$Interface\"}[30s]) + irate(ifInOctets{ifDescr=\"$Interface\"}[30s])) * 8 / ifSpeed{ifDescr=\"$Interface\"}"
    }
   ]
  },
  {
   "title": "Traffic detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "repeat": "Interface",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "$Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "In"
      },
      {
       "expr": "irate(ifHCInOctets{job='snmp-exporter',ifDescr=~'$Interface'}[5m])",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  }
 ]
}