{
 "title": "Otel - Node",
 "time": { "from": "2024-01-08T04:30:24.175Z", "to": "2024-01-08T08:30:24.175Z" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used RAM",
   "type": "gauge",
   "description": "Not taking cached RAM into account ",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{state=\"used\"}",
     "legendFormat": "{{job}} "
    }
   ]
  },
  {
   "title": "All used RAM",
   "type": "gauge",
   "description": "Kernel's 'free' memory",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - system_memory_utilization_ratio{state=\"free\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used disk space on /",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_utilization_ratio{mode=\"rw\", mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources - Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Free disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes{state=\"free\", mountpoint=\"/\"}",
     "legendFormat": "{{device}} - {{state}}"
    }
   ]
  },
  {
   "title": "Available disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - system_filesystem_utilization_ratio{mode=\"rw\"}",
     "legendFormat": "{{device}} Mounted on  {{mountpoint}}"
    }
   ]
  },
  { "title": "Resources - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(state) (system_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "instance" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg by(state) (system_cpu_utilization_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes - allocatable",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated (requests) Memory",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (k8s_node_name) (k8s_container_memory_request_bytes / avg without (k8s_node_uid, opencensus_resourcetype) (k8s_node_allocatable_memory_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Overprovisioned (limits) Memory",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (k8s_node_name) (k8s_container_memory_limit_bytes{k8s_node_name=\"$instance\"}) / avg without (k8s_node_uid, opencensus_resourcetype) (k8s_node_allocatable_memory_bytes{k8s_node_name=\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated (requests) CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (k8s_node_name) (k8s_container_cpu_request{k8s_node_name=\"$instance\"}) / avg without (k8s_node_uid, opencensus_resourcetype) (k8s_node_allocatable_cpu{k8s_node_name=\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Overprovisioned (limits) CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (k8s_node_name) (k8s_container_cpu_limit{k8s_node_name=\"$instance\"}) / avg without (k8s_node_uid, opencensus_resourcetype) (k8s_node_allocatable_cpu{k8s_node_name=\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory",
     "type": "timeseries",
     "description": "Metrics extracted using k8sclusterreceiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_node_allocatable_memory_bytes{k8s_node_name=\"$instance\"}",
       "legendFormat": "{{ k8s_node_name }} Allocatable Memory"
      },
      {
       "expr": "sum by (k8s_node_name) (k8s_container_memory_request_bytes{k8s_node_name=\"$instance\"})",
       "legendFormat": "{{ k8s_node_name }} Req Memory"
      },
      {
       "expr": "sum by (k8s_node_name) (k8s_container_memory_limit_bytes{k8s_node_name=\"$instance\"})",
       "legendFormat": "{{ k8s_node_name }} Limit Memory"
      }
     ]
    },
    {
     "title": "Allocated CPU",
     "type": "timeseries",
     "description": "Metrics extracted using k8sclusterreceiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "k8s_node_allocatable_cpu{k8s_node_name=\"$instance\"}",
       "legendFormat": "{{ k8s_node_name }} Allocatable CPU"
      },
      {
       "expr": "sum by (k8s_node_name) (k8s_container_cpu_request{k8s_node_name=\"$instance\"})",
       "legendFormat": "{{ k8s_node_name }} Req CPU"
      },
      {
       "expr": "sum by (k8s_node_name) (k8s_container_cpu_limit{k8s_node_name=\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Allocatable resources",
     "type": "timeseries",
     "description": "Metrics extracted using k8sclusterreceiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "k8s_node_allocatable_cpu{k8s_node_name=\"$instance\"}",
       "legendFormat": "{{ k8s_node_name }} Allocatable CPU"
      },
      {
       "expr": "k8s_node_allocatable_memory_bytes{k8s_node_name=\"$instance\"}",
       "legendFormat": "{{ k8s_node_name }} Allocatable Memory"
      }
     ]
    },
    {
     "title": "Allocatable resources (available)",
     "type": "timeseries",
     "description": "Metrics extracted using k8sclusterreceiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "k8s_node_memory_available_bytes{k8s_node_name=\"$instance\"}",
       "legendFormat": "{{ k8s_node_name }} Allocatable Memory"
      }
     ]
    }
   ]
  }
 ]
}