{
 "title": "Part 2 - SNMP Dashboard",
 "description": "Detailed interface stats from prometheus snmp exporter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifOperStatus, instance)"
    }
   },
   { "name": "ifName", "query": { "query": "ifOperStatus_ratio{}" } }
  ]
 },
 "panels": [
  {
   "title": "Connector Present",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifConnectorPresent_boolean{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} - on(instance) ifLastChange{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Admin Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus_ratio{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Oper Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus_ratio{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed_Mbps{instance=\"$instance\", ifName=\"$ifName\"} * 1000000"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu_MTU{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifType_InterfaceType{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutOctets_octets_total{instance=\"$instance\",ifName=\"$ifName\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifInOctets_octets_total{instance=\"$instance\",ifName=\"$ifName\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(ifOutOctets_octets_total[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifOutOctets_octets_total[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifOutOctets_octets_total[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifOutOctets_octets_total[$__range])",
     "legendFormat": "total in"
    },
    { "expr": "ifHighSpeed_Mbps", "legendFormat": "high speed" }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifInOctets_octets_total{instance=\"$instance\",ifName=\"$ifName\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifOutOctets_octets_total{instance=\"$instance\",ifName=\"$ifName\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifInOctets_octets_total{instance=\"$instance\",ifName=\"$ifName\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifOutOctets_octets_total{instance=\"$instance\",ifName=\"$ifName\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInUcastPkts_octets_total{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "rate(ifOutOctets_octets_total{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(rate(ifInOctets_octets_total{instance=\"$instance\", ifName=\"$ifName\"}[$__rate_interval]) * 8) or rate(ifInOctets_octets_total{instance=\"$instance\", ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "(rate(ifOutOctets_octets_total{instance=\"$instance\", ifName=\"$ifName\"}[$__rate_interval]) * 8) or rate(ifOutOctets{instance=\"$instance\", ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInErrors_total{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: errors: {{ifName}}"
    },
    {
     "expr": "rate(ifOutErrors_total{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: errors: {{ifName}}"
    }
   ]
  },
  {
   "title": "Broadcast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInBroadcastPkts_packets_total{instance=\"$instance\", ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "rate(ifOutBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInDiscards{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: discards: {{ifName}}"
    },
    {
     "expr": "rate(ifInUnknownProtos{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: unknown protos: {{ifName}}"
    },
    {
     "expr": "rate(ifOutDiscards{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: discards: {{ifName}}"
    }
   ]
  },
  {
   "title": "Multicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "rate(ifOutMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  }
 ]
}