{
 "title": "Part 2 - Docker Containers Metrics",
 "tags": [
  "Docker",
  "Containers"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "engine_host",
    "label": "Host ",
    "query": {
     "query": "label_values(docker_n_containers,engine_host)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name ",
    "query": {
     "query": "label_values(docker_container_cpu_throttling_periods{engine_host=~\"$engine_host\"}, container_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General - Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers{engine_host=~\"$engine_host\"}"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_images{engine_host=\"$engine_host\"}"
    }
   ]
  },
  {
   "title": "Containers Running ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers_running{engine_host=\"$engine_host\"}"
    }
   ]
  },
  {
   "title": "Containers Paused",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers_paused{engine_host=\"$engine_host\"}"
    }
   ]
  },
  {
   "title": "Containers Stopped ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers_stopped{engine_host=\"$engine_host\"}"
    }
   ]
  },
  {
   "title": "Live Threads ",
   "type": "stat",
   "description": "go routines are threads in go programming language",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_goroutines{engine_host=\"$engine_host\"}"
    }
   ]
  },
  {
   "title": "Total Network Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_container_net_rx_errors{engine_host=~\"$engine_host\"})\n+\nsum(docker_container_net_tx_errors{engine_host=~\"$engine_host\"})"
    }
   ]
  },
  {
   "title": "Total Memory Allocated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_memory_total{engine_host=\"$engine_host\"}"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_container_mem_usage{engine_host=\"$engine_host\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_container_mem_usage{engine_host=\"$engine_host\"})\n/\nsum(docker_memory_total{engine_host=\"$engine_host\"})"
    }
   ]
  },
  {
   "title": "Top Images CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5,docker_container_cpu_usage_percent{engine_host=\"$engine_host\"}) by (container_image))",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "Top Images Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5,docker_container_mem_usage{engine_host=\"$engine_host\"}) by (container_image))",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "Top Images Total Network Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5,\ndocker_container_net_rx_bytes{engine_host=\"$engine_host\"}\n+\ndocker_container_net_tx_bytes{engine_host=\"$engine_host\"}\n) by (container_image))",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  { "title": "Status - Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Container",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_status_uptime_ns{engine_host=\"$engine_host\",container_name=~\"$container_name\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_status_uptime_ns{engine_host=\"$engine_host\",container_name=~\"$container_name\"}"
    }
   ]
  },
  {
   "title": "Number Of OOOMKills ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_status_oomkilled{engine_host=\"$engine_host\",container_name=~\"$container_name\"}"
    }
   ]
  },
  { "title": "CPU - Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Time Throttled ",
   "type": "timeseries",
   "description": "Time in which cpu tries to go over the set limit ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "docker_container_cpu_throttling_throttled_time{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Memory - Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_usage{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "docker_container_mem_limit{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Cache Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_active_file{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - Active"
    },
    {
     "expr": "docker_container_mem_inactive_file{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - Inactive"
    }
   ]
  },
  {
   "title": "Anonymous Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_active_anon{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - Active"
    },
    {
     "expr": "docker_container_mem_inactive_anon{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - Inactive"
    }
   ]
  },
  {
   "title": "Memory Errors ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "docker_container_mem_pgmajfault{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} -  pgmajfault"
    },
    {
     "expr": "docker_container_mem_pgfault{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - pgfault"
    }
   ]
  },
  { "title": "Network - Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Sent & Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_net_rx_bytes{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} -  Received"
    },
    {
     "expr": "-docker_container_net_tx_bytes{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - Sent"
    }
   ]
  },
  {
   "title": "Sent & Received Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "docker_container_net_rx_errors{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} -  Received"
    },
    {
     "expr": "-docker_container_net_rx_errors{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - Sent"
    }
   ]
  },
  {
   "title": "Sent & Received Bytes Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "docker_container_net_tx_dropped{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} -  Sent"
    },
    {
     "expr": "docker_container_net_rx_dropped{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} -  Received"
    }
   ]
  },
  { "title": "I/O - Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Read & Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_blkio_io_service_bytes_recursive_write{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - Write"
    },
    {
     "expr": "-docker_container_blkio_io_service_bytes_recursive_read{engine_host=\"$engine_host\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} - Read"
    }
   ]
  }
 ]
}