{
 "title": "Linux OS Host Metrics - Custom",
 "tags": [
  "agent",
  "OS",
  "Windows"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Metrics Datasource", "query": "prometheus" },
   { "name": "logs", "label": "Logs Datasource", "query": "elasticsearch" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(process_cpu_time{os_type=\"linux\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(cpu) (system_cpu_utilization_ratio{state!=\"idle\"}))"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_usage_bytes{state=\"used\"}) / sum(system_memory_usage_bytes)"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_filesystem_usage_bytes{state!=\"free\"}) / sum(system_filesystem_usage_bytes)"
    }
   ]
  },
  { "title": "CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Utilization Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(host_name, cpu) (system_cpu_utilization_ratio{state!=\"idle\"})",
     "legendFormat": "{{host_name}} - {{cpu}}"
    }
   ]
  },
  {
   "title": "Current Top Processes By CPU Time Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(process_executable_name, state) (increase(process_cpu_time_seconds_total[$__rate_interval])))",
     "legendFormat": "{{process_executable_name}} - {{state}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_load_average_1m_ratio",
     "legendFormat": "{{host_name}} - load 1m"
    },
    {
     "expr": "system_cpu_load_average_5m_ratio",
     "legendFormat": "{{host_name}} - load 5m"
    },
    {
     "expr": "system_cpu_load_average_15m_ratio",
     "legendFormat": "{{host_name}} - load 15m"
    }
   ]
  },
  {
   "title": "CPU Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(host_name, state) (increase(system_cpu_time_seconds_total{state!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{host_name}} - {{state}}"
    }
   ]
  },
  { "title": "Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{state=\"used\"}",
     "legendFormat": "{{host_name}} - {{state}}"
    },
    { "expr": "sum(system_memory_usage_bytes)", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "Memory Usage (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_memory_usage_bytes", "legendFormat": "{{host_name}} - {{state}}" }
   ]
  },
  {
   "title": "Current Top Processes By Physical Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(process_executable_name) (process_memory_usage_bytes))",
     "legendFormat": "{{process_executable_name}} "
    }
   ]
  },
  {
   "title": "Current Top Processes By Virtual Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(process_executable_name) (process_memory_virtual_bytes))",
     "legendFormat": "{{process_executable_name}} "
    }
   ]
  },
  { "title": "Disk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Filesystem Bytes Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes",
     "legendFormat": "{{host_name}} - {{device}} - {{type}} - {{state}}"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "increase(system_disk_io_bytes_total{direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    },
    {
     "expr": "increase(system_disk_io_bytes_total{direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    }
   ]
  },
  {
   "title": "Current Top Processes By Disk I/O",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(process_executable_name) (increase(process_disk_io_bytes_total[$__rate_interval])))",
     "legendFormat": "{{process_executable_name}} "
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Network Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "system_network_connections", "legendFormat": "{{protocol}} - {{state}}" }
   ]
  },
  {
   "title": "NetworkRx/Tx Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "increase(system_network_io_bytes_total{direction=\"receive\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "increase(system_network_io_bytes_total{direction=\"transmit\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(system_network_packets_total{direction=\"receive\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "increase(system_network_packets_total{direction=\"transmit\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(system_network_errors_total{direction=\"receive\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "increase(system_network_errors_total{direction=\"transmit\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  { "title": "Activity Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Error Log Rate",
   "type": "timeseries",
   "description": "This query searches for specific keywords that may indicate the presence of an error. The keywords we seek include: error, abnormal, failure, failed, exception, and panic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:agent-linux AND (\"ERROR\" OR \"ABNORMAL\" OR \"FAILURE\" OR \"FAILED\" OR \"EXECEPTION\" OR \"PANIC\")",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:agent-windows",
     "timeField": "@timestamp"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Host Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "host_name:$host AND type:agent-linux",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}